### PR TITLE
feat(redteam): allow arbitrary providers

### PR DESCRIPTION
**Pull request by mldangelo**
### Summary

This update focuses on two main improvements for the redteam tests:

1. **Abstracted Provider Initialization**:
   - Refactored the code to remove hardcoded instances of `OpenAiChatCompletionProvider`. Use `loadApiProvider` instead to dynamically load and configure different API providers. This makes it easier to switch between various providers, like other OpenAI models or alternatives such as Ollama's `llama2-uncensored:latest` (providers like anthropic refuse to generate examples). 

2. **Enhanced Debug Messages**:
   - Improved the error message in the `getPurpose` function to provide more context when the purpose is not found.

### CODE REVIEW

**Review by typpo — COMMENTED** [review]
Looks pretty good!  Should we add a `-p, --provider` arg to `generate redteam` so the dev can override?

**Comment by typpo** [comment]
Another thought: we should use the default grading provider from `defaults.ts`.  That way it will have a fallback on systems that are configured for Claude/Gemini only.

**Review by typpo — APPROVED** [review]
Looks GREAT to me

**Comment by mannharleen** [comment]
Just in time... Awaiting the merge

**Comment by mannharleen** [comment]
On a related note: even the `promptfoo generate dataset` seems to be having the same issue. will this PR fix that too?

**Comment by mldangelo** [comment]
> On a related note: even the `promptfoo generate dataset` seems to be having the same issue. will this PR fix that too?

@mannharleen this is a great idea! I will add this tomorrow!

**Pull request merged**
