### PR TITLE
fix: Including prompt extraction broke redteam generation

### PR DESCRIPTION
**Pull request by sklein12**

### CODE REVIEW

**Comment by Mohit-Gaur** [comment]
@sklein12 Do you know if this fix will be included in a release in the near future?

I am facing the following error while running redteam generate even though the systemPrompt is configured.
```Error: Invariant failed: `systemPrompt` config is required for `prompt-extraction` plugin```

**Comment by typpo** [comment]
@Mohit-Gaur I believe this fix is included in 0.80.1

**Comment by Mohit-Gaur** [comment]
Ah ok. I am still facing this issue in 0.80.1. Guess I'll create a new issue

**Comment by Mohit-Gaur** [comment]
Gotcha thanks @typpo

**Comment by typpo** [comment]
0.80.2 will be published in a few min with this fix.  Let me know if you
run into any issues!

**Pull request merged**
