### PR TITLE
feat: add fal.ai provider

### PR DESCRIPTION
**Pull request by drochetti**
This PR introduces fal.ai image generation as a supported provider in promptfoo.

Quick example of a working configuration:

```yml
env:
  FAL_KEY: your_api_key_here
prompts:
  - a cat
  - a dog
  - a bird
providers:
  - id: fal:image:fal-ai/flux/schnell
    config:
      image_size:
        width: 1024
        height: 1024
      num_inference_steps: 8
      seed: 6252023
```

### CODE REVIEW

**Comment by mldangelo** [comment]
This is great! Thank you so much @drochetti. Have you given any thought to how we might be able to use this with assertions / metrics? I would love to think through a model graded metric https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/ for images and with a nice example that allows us to compare prompts. We'll work towards getting this in and released tomorrow.

**Comment by drochetti** [comment]
> This is great! Thank you so much @drochetti. Have you given any thought to how we might be able to use this with assertions / metrics? I would love to think through a model graded metric https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/ for images and with a nice example that allows us to compare prompts. We'll work towards getting this in and released tomorrow.

Hey @mldangelo, thank you for the quick follow up. That's a good question, I'm still learning promptfoo and all its capabilities, but I thought a few things could be useful reg. image (media in general) generation:

1. check / compare inference time
2. test whether the inference time is below a certain duration threshold
3. use a vllm to check prompt adherence (it would be super cool but I'm not sure how to accomplish it tbh)
4. last but not list, if we could make the result table a bit more friendly to images, it's useful to manually compare results to check how different models behave against the same prompt/options

For now, I'm doing number 4, using the markdown rendering. Even though the UI isn't ideal, it already offer some good value!

Thoughts?

**Comment by mldangelo** [comment]
Hey @drochetti,

You're doing a fantastic job learning Promptfoo! Regarding your suggestions:

1 & 2. We support these assertions out of the box. You can use:

```yaml
    assert:
      - type: latency
        threshold: 3000  # milliseconds
      - type: cost
        threshold: 0.001
```

3. It would be awesome to extend `llm-rubric` or create a new metric similar to what we use for text outputs, like this:

    ```yaml
    assert:
      - type: llm-rubric
        value: is an image of a cat
    ```

   You can check out our existing [LLM rubric metric documentation](https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/llm-rubric/) for more details. Adapting this for images would be very interesting. I’m also curious to know what model-graded metrics you use to evaluate outputs.

4. **Improving the Result Table for Images**: Absolutely agree. @mrflounder has an [open PR for input transforms](https://github.com/promptfoo/promptfoo/pull/1704) that makes it easier to view input images from storage buckets or URLs. It would be great to get your thoughts on how we can better display images.

If you know of any other metrics you use at fal.ai or have additional ideas, we’re happy to work on supporting them as well. Also, if you're interested, we’d love to collaborate on a guide for evaluating multimodal inputs, whether it’s for Promptfoo or your site. We can cross-link and share the knowledge with the community—whatever works best for you.

Thanks again for extending your work to Promptfoo. You’re doing amazing work, and we really appreciate your contributions!

**Comment by drochetti** [comment]
Thank for all the context @mldangelo, that great. Regarding number 4, I looked at the open PR and that's great news! Currently I transformed our JSON response to a Markdown string like Replicate did for their image provider, but I'm happy to submit a PR as soon as the input transforms lands, to update it.

In the meantime, do you think we can merge the PR as is? I'm asking because we have a big customer who uses promptfoo and would love to have fal in there as a plug-and-play provider.

**Comment by mldangelo** [comment]
@drochetti 

Can you merge `@fal-ai/serverless-client` into a peer dependency and we'll get it merged and released ASAP. Take a look at https://www.promptfoo.dev/docs/providers/aws-bedrock/ as an example for how we use peer dependencies for providers. Everything else looks good! 

Thank you!

**Comment by typpo** [comment]
One other small request: can we do `FAL_API_KEY` for consistency with other providers, unless fal.ai itself has a convention of naming it `FAL_KEY`?

**Comment by drochetti** [comment]
> @drochetti
> 
> Can you merge `@fal-ai/serverless-client` into a peer dependency and we'll get it merged and released ASAP. Take a look at https://www.promptfoo.dev/docs/providers/aws-bedrock/ as an example for how we use peer dependencies for providers. Everything else looks good!
> 
> Thank you!

Done!

**Review by mldangelo — APPROVED** [review]

**Pull request merged**
