### PR TITLE
feat: Add Cloudflare AI Provider

### LINKED ISSUE #647: Support Cloudflare Workers AI
Leaving a ticket here for something I want to implement shortly: supporting cf workers AI.

They have beta support for uploading lora finetunes and could support very low latencies. So I think it's a great target to support in promptfoo.

### PR DESCRIPTION
**Pull request by jacobdr**
Closes #647

[Cloudflare Workers AI](https://developers.cloudflare.com/workers-ai/) provider implementation

===

This is a work in progress I wanted to put up for initial feedback. I still need to test it a bunch more locally and update the docs as well.

### CODE REVIEW

**Comment by jacobdr** [comment]
@typpo Anything else major besides docs that you think might be missing, assuming a correct implementation on my part of the CF API calls?

**Comment by jacobdr** [comment]
Note to self, look at https://github.com/promptfoo/promptfoo/pull/711/files for inspiration on examples + docs

**Comment by jacobdr** [comment]
@typpo the line changes related to formatting are due to VS code auto-format. I tried to remove then by running `npm run format` but that command generated a MASSIVE diff so I think you might want to consider enforcing the styling in CI in a separate effort

**Comment by typpo** [comment]
Nice change!  This looks pretty much ready to go.  Hopefully @CamdenClark can find the time to verify this weekend, otherwise I'll figure out how to get myself set up on Cloudflare AI :)

**Comment by CamdenClark** [comment]
> Nice change! This looks pretty much ready to go. Hopefully @CamdenClark can find the time to verify this weekend, otherwise I'll figure out how to get myself set up on Cloudflare AI :)

I got to it! It works on my machine!

Thanks for taking this up, I got super distracted and forgot to do it :sweat: 

In the future it would be cool to get LoRA support but that's not necessary to merge in my opinion.

Feel free to tag me on a non-draft PR if you want another review.

**Comment by CamdenClark** [comment]
one other thing you might want to know -- I had to build promptfoo on a new machine with node 22 and I got some weird C++ errors with better-sqlite. Might want to put a note recommending node 20

**Comment by jacobdr** [comment]
@CamdenClark thanks for testing for me....

@typpo im working now on the docco after fixing the failing tests today. Would you mind please re-triggering the CI test workflow so that I can verify that worked? Assuming thats green, and once I push one more commit for the docs and a few more examples, then this should be good to go (though I'll do a final rebase against master before un-drafting it)

**Comment by jacobdr** [comment]
@typpo this is now done and awaiting final review + green CI

**Review by typpo — APPROVED** [review]
This change looks excellent!  Nice work!  Just waiting for green CI and will land it ✨

**Comment by typpo** [comment]
🎉 Amazing work @jacobdr and thanks @CamdenClark for helping too!

**Pull request merged**
