### PR TITLE
feat: helm chart for self hosted

### PR DESCRIPTION
**Pull request by didlawowo**
I have made a working helm chart to provide self hosted promptfoo for team sharing

### CODE REVIEW

**Comment by mldangelo** [comment]
@didlawowo thank you so much for contributing this! Would you mind taking a quick pass at `site/docs/usage/self-hosting.md` with instructions for getting it up and going?

I hope you don't mind that I fixed the lint. 

What's the best way to test your branch?  I tried with minikube but ran into errors around `{ {` vs `{{` in your yaml templates.

**Comment by didlawowo** [comment]
> @didlawowo thank you so much for contributing this! Would you mind taking a quick pass at `site/docs/usage/self-hosting.md` with instructions for getting it up and going?
> 
> I hope you don't mind that I fixed the lint.
> 
> What's the best way to test your branch? I tried with minikube but ran into errors around `{ {` vs `{{` in your yaml templates.

it's curious because i don't have error on my cluster.

i'm using argo cd app somethings like this but a simple helm install with some value custom should work.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promptfoo
  namespace: kube-infra
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  project: mlops
  source:
    repoURL: git@github.com:xxxxx/continuous-delivery.git

    targetRevision: main
    path: charts/promptfoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

**Comment by didlawowo** [comment]
i have added pvc persistence

**Comment by mldangelo** [comment]
Thank you @didlawowo

**Pull request merged**
