### PR TITLE
feat(ai21): Add AI21 Labs provider

### PR DESCRIPTION
**Pull request by streichsbaer**
## Changelog
This PR adds support for the AI21 Labs provider.

AI21 has released the Jamba 1.5 model family, the first frontier-grade hybrid SSM-Transformer instruction following models.

- [x] All API parameters are covered
- [x] The model pricing is included
- [x] Caching is supported

An account with a free trial (10$ credits) can be created at:
- https://studio.ai21.com/login

## Testing
My local setup is broken and I couldn't test my changes.
Have there been any changes in how to run local changes with `npx /path/to/promptfoo`?
I also tried using the `npm link` approach which gives me:
```
/path/to/streichsbaer/promptfoo/dist/src/commands/eval.js:115
        const testSuiteSchema = types_1.TestSuiteSchema.safeParse(testSuite);
                                                        ^

TypeError: Cannot read properties of undefined (reading 'safeParse')
    at runEvaluation (/path/to/streichsbaer/promptfoo/dist/src/commands/eval.js:115:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doEval (/path/to/streichsbaer/promptfoo/dist/src/commands/eval.js:260:5)

Node.js v20.14.0
```

### CODE REVIEW

**Comment by mldangelo** [comment]
Thanks so much for putting this together, @streichsbaer!

Re. local testing. There have not been any changes. Instead of running `npm run build:watch` (or `npm run build`) and then `promptfoo eval`, you can run `npm run local -- eval`. If it's still not working, let's hop on a call (https://cal.com/michael-dangelo/30min)

Great work on this, and thanks again for your contribution! I will test it out in the morning.

**Comment by streichsbaer** [comment]
My pleasure, @mldangelo!

Just ran `npm run local --eval -c ...` and it's all working 👍 
image

**Comment by typpo** [comment]
Very nice, thanks @streichsbaer!

**Comment by typpo** [comment]
The composer is 🔥 !

**Pull request merged**
