### PR TITLE
chore(deps): replace rouge with js-rouge

### PR DESCRIPTION
**Pull request by QuarkNerd**
To make onboarding easier into certain systems I use, It would be helpful to have pacakges come from npm,.
I have cloned the github repo for rouge, upped the version and pushed to npm, this should hopefully have no effect on most people using this package but make it easier to use in some cases.

### CODE REVIEW

**Comment by mldangelo** [comment]
Thanks @QuarkNerd! Would you mind moving the type annotations into your package as well? I started a ts rewrite of rouge a few months ago: https://github.com/mldangelo/rouge you are free to copy from that as well if you’d like (but no obligation). 

If you’re open to it, we could move js-rouge into the promptfoo npm and/or GitHub orgs too. 

Thanks!

**Comment by QuarkNerd** [comment]
I can merge your branch into mine, but I'm happy to let promptfoo take control of the GitHub/npm since I don't really know much about rouge. Would it be easier for you to take control and then make your changes as you see fit? I'm happy either way.

**Comment by mldangelo** [comment]
@QuarkNerd can you give mdangelo permissions to modify your npm package?

**Comment by QuarkNerd** [comment]
I've sent you a request

**Comment by mldangelo** [comment]
Thanks, @QuarkNerd for suggesting this and driving it!  I switched it over to a ts fork https://github.com/promptfoo/rouge hosted at promptfoo! Happy to add you as a contributor to the ts fork if you would like to make other improvements.

**Pull request merged**
