### PR TITLE
feat(provider/openai): support loading response_format from a file

### PR DESCRIPTION
**Pull request by albertlieyingadrian**
Context: https://github.com/promptfoo/promptfoo/issues/1710

### CODE REVIEW

**Comment by albertlieyingadrian** [comment]
Do we have unit test coverage for openAI provider? Wasn't able to find it @mldangelo

**Comment by mldangelo** [comment]
This looks great thank you. 

FYI, unit tests for openai are all in `test/providers.test.ts`! I plan to split them out at some point in the future.

**Comment by albertlieyingadrian** [comment]
Thanks, when is this going to be published? @mldangelo

**Comment by albertlieyingadrian** [comment]
Gotcha, thanks! @mldangelo

**Pull request merged**
