### PR TITLE
fix(util/json): fix jsonExtraction when generating dataset

### PR DESCRIPTION
**Pull request by albertlieyingadrian**
Context https://github.com/promptfoo/promptfoo/issues/1673

### CODE REVIEW

**Comment by typpo** [comment]
Thanks @albertlieyingadrian!  This is a great catch, should we add your input as a test case as well?

**Comment by albertlieyingadrian** [comment]
It failed other test cases :\ @mldangelo

**Comment by mldangelo** [comment]
Thanks for the fix, @albertlieyingadrian! Could you take a look at the test failures in `test/util.json.test.ts`? I think the tests are correct as is, and they might help identify any edge cases that still need addressing. Let me know what you find or if you'd like help!

**Comment by albertlieyingadrian** [comment]
Moved this PR here https://github.com/promptfoo/promptfoo/pull/1687

**Pull request closed without merging**
