### PR TITLE
feat: global `env` var in templates

### PR DESCRIPTION
**Pull request by typpo**
Related to #1552

### CODE REVIEW

**Review by mldangelo — APPROVED** [review]
good solution. Please consider adding a unit test

**Comment by AmineDjeghri** [comment]
Thank you !

**Comment by AmineDjeghri** [comment]
Hello
i just tried it and it doesn't work for me

i have promptfoo latest version and here is a small example how i did it : 

image

**Comment by AmineDjeghri** [comment]
i would like to know also, if it works in the providers.
Because the purpose is to use is in the providers config like this : 

id: azureopenai:chat:gpt-4o-mini
config:
  apiHost: '{{env.AZURE_OPENAI_API_ENDPOINT}}'

**Comment by typpo** [comment]
@AmineDjeghri  No, it won't work for providers.  The provider expects a specific environment variable for that: `AZURE_OPENAI_API_HOST`

**Comment by AmineDjeghri** [comment]
are you sure AZURE_OPENAI_API_HOST exists and works?  I've tried it and it doesn't work for me. 
It's also not mentioned here 
the reason i created this issue is the absence of some env variables, and instead of waiting for the maintainers to add them, we can add our own env variables

**Pull request merged**
